---
abstract: 'Plack application for message board.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Message-Board
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Data::HTML::Element::A: 0
  Data::HTML::Footer: 0
  Data::Message::Board: 0
  Data::Message::Board::Comment: 0
  Data::Message::Simple: 0
  DateTime: 0
  Exporter: 0
  Plack::App::CPAN::Changes: 0
  Plack::App::URLMap: 0
  Plack::Component: 0
  Plack::Component::Tags::HTML: 0.15
  Plack::Request: 0
  Plack::Response: 0
  Plack::Session: 0
  Plack::Util::Accessor: 0
  Readonly: 0
  Tags::HTML::Container: 0
  Tags::HTML::Footer: 0
  Tags::HTML::Message::Board: 0.05
  Tags::HTML::Message::Board::Blank: 0.05
  Tags::HTML::Messages: 0
  Tags::HTML::Table::View: 0
  Unicode::UTF8: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Plack-App-Message-Board/issues
  homepage: https://github.com/michal-josef-spacek/Plack-App-Message-Board
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Plack-App-Message-Board
version: '0.03'
